export const LOGO_COMPANY_DATA_LIST = [
  {id: 1, name: "1", format: "svg"},
  {id: 2, name: "2", format: "svg"},
  {id: 3, name: "3", format: "svg"},
  {id: 4, name: "4", format: "svg"},
  {id: 5, name: "5", format: "svg"},
  {id: 6, name: "6", format: "svg"},
  {id: 7, name: "7", format: "svg"},
  {id: 8, name: "8", format: "svg"},
  {id: 9, name: "9", format: "svg"},
  {id: 10, name: "10", format: "svg"},
  {id: 11, name: "11", format: "svg"},
  {id: 12, name: "12", format: "svg"},
  {id: 13, name: "13", format: "svg"},
  {id: 14, name: "14", format: "svg"},
  {id: 15, name: "15", format: "svg"},
  {id: 16, name: "16", format: "svg"},
  {id: 17, name: "17", format: "svg"},
  {id: 18, name: "18", format: "svg"},
  {id: 19, name: "19", format: "svg"},
];