export const USE_IS_HOUSE_DATA_LIST = [
  {
    id: 1,
    imgName: "/about_platform-1.png",
    sup: "",
    title: "Information Synthesis",
    p: "Quickly synthesize contract implications, regulatory updates, and key findings to drive informed decisions—with text-level citations from source documents.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 2,
    imgName: "about_platform-2.png",
    sup: "",
    title: "Litigation & Risk Management",
    p: "Receive insights into recommended strategies for litigation and investigations, and identify potential liabilities and risks to your organization.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 3,
    imgName: "about_platform-3.png",
    sup: "",
    title: "Regulatory Compliance",
    p: "Analyze evolving global regulations, track changes over time, and ensure internal policies and operations stay aligned with legal and regulatory requirements.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 4,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Contracting",
    p: "Review contracts against a preferred playbook, form, or template, and receive drafting suggestions to implement in tracked changes.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 5,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Legal Operations",
    p: "Track key dates and contractual obligations, plus categorize and filter contract clauses and document types.",
    a: "",
    to: "/",
    className: "",
  },
   {
    id: 6,
    imgName: "/about_platform-1.png",
    sup: "",
    title: "Internal Communication",
    p: "Translate legal jargon into plain-language summaries, FAQs, and memos to inform and align with business stakeholders.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 7,
    imgName: "about_platform-2.png",
    sup: "",
    title: "Strategic Research Analysis",
    p: "Navigate complex EU regulations with AI trained on EUR-Lex and other jurisdiction-specific sources.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 8,
    imgName: "about_platform-3.png",
    sup: "",
    title: "Public Company Research",
    p: "Analyze trends, disclosures, and required filings through integrated access to EDGAR.",
    a: "",
    to: "/",
    className: "",
  },

]