export const USE_LITIGATION_DATA_LIST = [
  {
    id: 1,
    imgName: "/about_platform-1.png",
    sup: "",
    title: "Case Assessment",
    p: "Swiftly evaluate complaints, create chronologies, and identify gaps in factual and legal analysis.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 2,
    imgName: "about_platform-2.png",
    sup: "",
    title: "Discovery",
    p: "Review and categorize large volumes of documents, analyze expert work and deposition transcripts, and organize discovery materials efficiently.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 3,
    imgName: "about_platform-3.png",
    sup: "",
    title: "Analysis",
    p: "Conduct comprehensive analysis more quickly by using Harvey to synthesize legal principles across multiple cases.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 4,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Drafting",
    p: "Instantly generate first drafts, enabling more concise and persuasive pleadings, motions, legal briefs, and client memos.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 5,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Trial Preparation",
    p: "Optimize trial strategy by analyzing opposing counsel's case and identifying ways to address gaps, such as refining legal arguments and filing additional pre-trial motions.",
    a: "",
    to: "/",
    className: "",
  },
   {
    id: 6,
    imgName: "/about_platform-1.png",
    sup: "",
    title: "Strategic Advice",
    p: "Draft post-judgment communications and strategize grounds for appeal by analyzing court decisions and generating compelling arguments.",
    a: "",
    to: "/",
    className: "",
  },

]