export const USE_TRANSACRIONAL_DATA_LIST = [
  {
    id: 1,
    imgName: "/about_platform-1.png",
    sup: "",
    title: "Client Engagement and Prospecting",
    p: "Draft client alerts and build thought leadership to reach potential new clients and deepen existing client relationships.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 2,
    imgName: "about_platform-2.png",
    sup: "",
    title: "Due Diligence",
    p: "Minimize tedious tasks by streamlining document review, surfacing critical insights and identifying key risks over thousands of documents at a time, no matter the language or governing law jurisdiction.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 3,
    imgName: "about_platform-3.png",
    sup: "",
    title: "Drafting",
    p: "Strengthen contractual clauses and check for inconsistencies in drafts based on precedents, forms, playbooks, or deal points, allowing you to focus on strategic decisions and deal execution.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 4,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Research",
    p: "Access public company filings from the SEC’s EDGAR database to make informed decisions on transactions, negotiations or governance matters.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 5,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Negotiation",
    p: "Improve negotiations by generating issues lists with recommendations for your client to finalize deal documents more quickly.",
    a: "",
    to: "/",
    className: "",
  },
   {
    id: 6,
    imgName: "/about_platform-1.png",
    sup: "",
    title: "Deal Management",
    p: "Generate checklists and extract deadlines to streamline execution at all deal stages.",
    a: "",
    to: "/",
    className: "",
  },

]