export const USE_INOVATION_DATA_LIST = [
  {
    id: 1,
    imgName: "/about_platform-1.png",
    sup: "",
    title: "Custom Workflows",
    p: "Design and deploy one-click workflows that reflect the way your firm works, tailored to your team’s practice areas and priorities.",
    a: "",
    to: "/",
    className: "flex-row-reverse",
  },
  {
    id: 2,
    imgName: "about_platform-2.png",
    sup: "",
    title: "Tailored to Your Expertise",
    p: "Turn your firm’s proprietary knowledge and expertise into living AI resources—accessible firmwide for consistent, high-quality work.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 3,
    imgName: "about_platform-3.png",
    sup: "",
    title: "Track Adoption",
    p: "Get visibility into who is using Harvey and how they’re using it to measure impact and demonstrate ROI to leadership.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 4,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Collaboration and Sharing",
    p: "Enable attorneys to build on each other’s work in real time—accelerating delivery while staying aligned across your firm and with your clients.",
    a: "",
    to: "/",
    className: "",
  },
  {
    id: 5,
    imgName: "about_platform-4.png",
    sup: "",
    title: "Compliance",
    p: "Control access and log activity with built-in permissions and audit trails, ensuring firmwide compliance.",
    a: "",
    to: "/",
    className: "",
  },

]