export const USE_PLATFORM_DATA_LIST = [
  {
    id: 1,
    imgName: "1.svg",
    sup: "Assistant",
    title: "Tailored to Your Expertise",
    p: "Delegate complex tasks in natural language to your domain-specific personal assistant.",
    a: "Explore Assistant",
    to: "/",
    className: "",
  },
    {
    id: 2,
    imgName: "4.svg",
    sup: "Assistant",
    title: "Tailored to Your Expertise",
    p: "Delegate complex tasks in natural language to your domain-specific personal assistant.",
    a: "Explore Assistant",
    to: "/",
    className: "",
  },
    {
    id: 3,
    imgName: "6.svg",
    sup: "Assistant",
    title: "Tailored to Your Expertise",
    p: "Delegate complex tasks in natural language to your domain-specific personal assistant.",
    a: "Explore Assistant",
    to: "/",
    className: "",
  },
    {
    id: 4,
    imgName: "7.svg",
    sup: "Assistant",
    title: "Tailored to Your Expertise",
    p: "Delegate complex tasks in natural language to your domain-specific personal assistant.",
    a: "Explore Assistant",
    to: "/",
    className: "",
  },
  
]